---
dashboard: false
# By default, Pod cannot be scheduled on the master node.
# However, if you set the master_node_schedulable variable
# to true, Kubernetes will deploy Pod even on master node.
# This functionality could be useful to reduce the number of VM
# to create.
master_node_schedulable: true
servers:
# Make sure the master node is always the first in the list.
- name: k8s-master
  type: master
  box: ubuntu/bionic64
  box_version: 20190411.0.0
  eth1: 192.168.56.4
  mem: 2048
  cpu: 2
- name: k8s-worker-1
  type: worker
  box: ubuntu/bionic64
  box_version: 20190411.0.0
  eth1: 192.168.56.5
  mem: 2048
  cpu: 2
- name: k8s-worker-2
  type: worker
  box: ubuntu/bionic64
  box_version: 20190411.0.0
  eth1: 192.168.56.6
  mem: 2048
  cpu: 2
